config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/edit'
  get 'password_resets/new'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get '/help',      to: 'static_pages#help'
  get '/about',     to: 'static_pages#about'
  get '/contact',   to: 'static_pages#contact'
  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'appointments/edit', to: 'appointments#update'
  resources :comments
  resources :users do
    member do
      get :following, :followers
      get :appointments
      get :comments
    end
    resources :comments
    resources :appointments do
      member do
        get :comments
      end
      resources :comments
    end
  end
  resources :appointments do
    member do
      get :comments
    end
    resources :comments
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
end

app/views/shared/_appointment_form.html.erb
<%= form_for(@appointment) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class='field'>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'Name', class: 'form-control' %>

    <%= f.label :start_time %>
    <%= f.datetime_field :start_time, class: 'form-control' %>
    
    <%= f.label :end_time %>
    <%= f.datetime_field :end_time, class: 'form-control' %>
    
    <%= f.label :location %>
    <%= f.text_field :location, placeholder: 'Location', class: 'form-control' %>

    <%= f.label :phone_number%>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>
  <%= f.submit 'Post', class: 'btn btn-primary' %>
<% end %>

app/views/shared/_comment_form.html.erb
<%= form_for([appointment, @comment]) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class='field'>
    <%= f.text_area :content, placeholder: 'Compose new comment...' %>
  </div>
  <%= f.submit 'Post', class: 'btn btn-primary' %>
<% end %>

app/views/shared/_edit_form.html.erb
<%= form_for(@appointment) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class='field'>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'Name', class: 'form-control' %>
  
    <%= f.label :start_time %>
    <%= f.datetime_field :start_time, class: 'form-control' %>
    
    <%= f.label :end_time %>
    <%= f.datetime_field :end_time, class: 'form-control' %>
  
    <%= f.label :location %>
    <%= f.text_field :location, placeholder: 'Location', class: 'form-control' %>
  
    <%= f.label :phone_number%>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>
  <%= f.submit 'Save changes', class: 'btn btn-primary' %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id='error explanation'>
    <div class='alert alert-danger'>
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class='appointments'>
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% else %>
<div class='container jumbotron col-md-8'>
  Start following other <%= link_to 'Users', users_path %> to populate your feed!
</div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class='stats'>
  <a href="<%= following_user_path(@user) %>">
    <strong id='following' class='stat'>
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id='followers' class='stat'>
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to 'view my profile', current_user %></span>