config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/edit'
  get 'password_resets/new'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get '/help',      to: 'static_pages#help'
  get '/about',     to: 'static_pages#about'
  get '/contact',   to: 'static_pages#contact'
  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'appointments/edit', to: 'appointments#update'
  resources :comments
  resources :users do
    member do
      get :following, :followers
      get :appointments
      get :comments
    end
    resources :comments
    resources :appointments do
      member do
        get :comments
      end
      resources :comments
    end
  end
  resources :appointments do
    member do
      get :comments
    end
    resources :comments
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
end

app/models/appointment.rb
# /app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  before_validation :strip_phone
  default_scope(-> { order(created_at: :desc) })
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 140 }
  validates :location, length: { maximum: 140 }
  validates :start_time, presence: true
  validates_datetime :end_time, :end_time, after: :start_time
  validates :phone_number, length: { minimum: 10 },
                           format: { with: /[0-9._]/,
                                     message: 'Can only contain numbers.' }
  after_create :reminder
  after_create :alert

  # Notify our appointment attendee X minutes before the appointment time

  def twilio_keys
    @twilio_number = Rails.application.secrets.TWILIO_NUMBER
    @client =
      Twilio::REST::Client.new Rails.application.secrets.TWILIO_ACCOUNT_SID,
                               Rails.application.secrets.TWILIO_AUTH_TOKEN
  end

  def reminder
    time_str = convert_time(start_time)
    reminder = "Hi #{user.name}.
    Just a reminder that you have an appointment coming up at
    #{time_str}"
    twilio_keys
    message_template(reminder)
  end

  def when_to_run_reminder
    start_time - 60.minutes
  end

  handle_asynchronously :reminder, run_at: proc { |i| i.when_to_run_reminder }

  def alert
    time_str = convert_time(start_time)
    alert = "Hi #{user.name}.
    Just a reminder that you have an appointment that just started at
    #{time_str}."
    twilio_keys
    message_template(alert)
  end

  def message_template(message)
    message = @client.account.messages.create(
      from:  @twilio_number,
      to: ('1' + user[:phone]),
      body: message
    )
    log message.to
  end

  def when_to_run_alert
    start_time
  end

  handle_asynchronously :alert, run_at: proc { |i| i.when_to_run_alert }

  def find_time
    distance_of_time_in_words(Time.zone.now, due_at)
  end

  def convert_time(datetime)
    datetime.strftime('%I:%M %P on %b. %d, %Y')
  end

  def strip_phone
    phone_number.gsub!(/[^0-9]/, '')
  end

  # Returns a appointment's status feed.
  def feed
    comment_ids = "SELECT id FROM comments
                     WHERE appointment_id = :appointment_id"
    Comment.where("id IN (#{comment_ids})
                     OR id = :appointment_id", appointment_id: id)
  end
end

app/controllers/appointments_controller.rb
# /app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :update]
  before_action :correct_user,   only: :destroy
  before_action :admin_user,     only: :destroy

  def create
    @appointment = current_user.appointments.build(appointment_params)
    if @appointment.save
      flash[:success] = 'Appointment created!'
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def edit
    @appointment = current_user.appointments.find_by(id: params[:id])
  end

  def update
    @appointment = current_user.appointments.find_by(id: params[:id])
    if @appointment.update_attributes(appointment_params)
      flash[:success] = 'Appointment updated!'
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def show
    @user = User.find_by(id: params[:format])
    @appointment = @user.appointments.find_by(id: params[:id])
    commenting
  end

  def commenting
    @comment = current_user.comments.build(params[:comment]) if logged_in?
    @comments = @appointment.feed.paginate(page: params[:page])
  end

  def destroy
    @appointment.destroy
    flash[:success] = 'Appointment deleted'
    redirect_to request.referer || root_url
  end

  private

  def appointment_params
    params.require(:appointment).permit(:name,
                                        :start_time,
                                        :end_time,
                                        :location,
                                        :phone_number)
  end

  def correct_user
    @appointment = current_user.appointments.find_by(id: params[:id])
    redirect_to root_url if @appointment.nil?
  end

  # Confimrs admin user
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/appointments_helper.rb
# /app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_appointment.html.erb
<li class='container' id='appointment-<%= appointment.id %>'>
  <div class='container col-md-2'>
    <%= link_to gravatar_for(appointment.user, size: 80), appointment.user %>
    <span class='user'>
      <%= link_to appointment.user.name, appointment.user %>
    </span>
  </div>
  <span class='container col-md-6'>
    Meeting with: <%= appointment.name %>
    <% if current_user?(appointment.user) %>
    <span class='pull-right'>
        <%= link_to 'Update', edit_appointment_path(appointment.id) %>
        <%= link_to 'Delete', appointment, method: :delete,
                              data: { confirm: 'You sure?' } %>
    </span></br>
    <span class='pull-right'>
        <%= link_to 'Comments', appointment_path(appointment.user_id, id: appointment.id) %>
        (<%= appointment.comments.count %>)
    </span></br>
    At: <%= appointment.convert_time(appointment.start_time) %></br>
    Until: <%= appointment.convert_time(appointment.end_time) %></br>
    Phone Number: <%= number_to_phone(appointment.phone_number) %></br>
    Where: <%= appointment.location %></br>
    <% elsif %>
    <div>
      <span class='pull-right'>
        <%= link_to 'Comments', appointment_path(appointment.user_id, id: appointment.id) %> 
        (<%= appointment.comments.count %>)
      </span>
      In: <%= distance_of_time_in_words_to_now(appointment.start_time) %>
    </div>
    <div>
    </div>
    <% end %>
  </span>
</li>

app/views/appointments/_appointment_show.html.erb
<% provide(:title, @appointment.name + ' | Appointment') %>
<div class='container' id='appointment-<%= @appointment.id %>'>
  <div class='container col-md-4'>
    <%= link_to gravatar_for(@appointment.user, size: 80), @appointment.user %>
    <span class='user'>
      <%= link_to @appointment.user.name, @appointment.user %>
    </span>
  </div>
  <span class='container col-me-8'>
    Meeting with: <%= @appointment.name %>
    <% if current_user?(@appointment.user) %>
    <span class='pull-right'>
        <%= link_to 'Update', edit_appointment_path %>
        <%= link_to 'Delete', @appointment, method: :delete,
                              data: { confirm: 'You sure?' } %>
    </span></br>
    At: <%= @appointment.convert_time(@appointment.start_time) %></br>
    
    Phone Number: <%= number_to_phone(@appointment.phone_number) %></br>
    
    Where: <%= @appointment.location %></br>
    
    <% elsif %>
    <div>
    In: <%= distance_of_time_in_words_to_now(@appointment.start_time) %>
    </div>
    <% end %>
  </span>
</div>
<span class='container'>
  <div class='col-md-8'>
    <% if @appointment.comments.any? %>
      <h3>Comments (<%= @appointment.comments.count %>)</h3>
      <ol class='comments'>
      <%= render @comments %>
      </ol>
      <%= will_paginate @comments %>
    <% else %>
    <label class='form-label'>
    No comments yet
    </label>
    <% end %>
  </div>
   <div><%= render 'shared/comment_form', user: current_user, 
                                          appointment: @appointment %>
  </div>
</span>

app/views/appointments/edit.html.erb
<% provide(:title, 'Update Appointment') %>
<h1>Update your appointment</h1>

<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <%= render 'shared/edit_form' %>
</div>

app/views/appointments/show.html.erb
<%= render 'appointments/appointment_show' %>